"""Add the org properties table

Revision ID: 0b916a280427
Revises: e830eb163d38
Create Date: 2018-08-04 11:49:01.958895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b916a280427'
down_revision = 'e830eb163d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_properties',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=511), nullable=False),
    sa.Column('property_value', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('STRING', 'NUMBER', 'JSON', 'BOOLEAN', name='orgpropertytypes'), nullable=False),
    sa.Column('property_namespace', sa.Enum('NONE', 'GATES', 'THEME', 'SETTINGS', name='orgpropertynamespaces'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'property_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orgs_client_secret_key', 'orgs', ['client_secret'])
    op.create_unique_constraint('orgs_client_id_key', 'orgs', ['client_id'])
    op.drop_table('org_properties')
    # ### end Alembic commands ###
