"""Add orgs and make users have an org ID.

Revision ID: 26afe8245b5e
Revises: 4967dd886a37
Create Date: 2018-07-15 17:41:22.038133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26afe8245b5e'
down_revision = '4967dd886a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'orgs', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'org_id')
    op.drop_table('orgs')
    # ### end Alembic commands ###
