"""Adds type to the end user properties table

Revision ID: 335498e86d07
Revises: 4cbb0848ec97
Create Date: 2018-10-22 08:14:19.863223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '335498e86d07'
down_revision = '4cbb0848ec97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enduserpropertytypes = postgresql.ENUM('STRING', 'NUMBER', 'JSON', 'BOOLEAN', name='enduserpropertytypes')
    enduserpropertytypes.create(op.get_bind())
    op.add_column('end_user_properties', sa.Column('property_type', sa.Enum('STRING', 'NUMBER', 'JSON', 'BOOLEAN', name='enduserpropertytypes'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('end_user_properties', 'property_type')
    enduserpropertytypes = postgresql.ENUM('STRING', 'NUMBER', 'JSON', 'BOOLEAN', name='enduserpropertytypes')
    enduserpropertytypes.drop(op.get_bind())
    # ### end Alembic commands ###
