"""Adds the google_id field to end users

Revision ID: 373d888b4475
Revises: 335498e86d07
Create Date: 2019-01-23 10:50:17.833936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373d888b4475'
down_revision = '335498e86d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('google_id', sa.String(length=90), nullable=True))
    op.create_index(op.f('ix_end_users_google_id'), 'end_users', ['google_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_end_users_google_id'), table_name='end_users')
    op.drop_column('end_users', 'google_id')
    # ### end Alembic commands ###
