"""empty message

Revision ID: 4967dd886a37
Revises: 
Create Date: 2018-07-15 17:04:47.466082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4967dd886a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('users_email_auth_token',
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token', 'user_id')
    )
    op.create_index(op.f('ix_users_email_auth_token_active'), 'users_email_auth_token', ['active'], unique=False)
    op.create_index(op.f('ix_users_email_auth_token_sent'), 'users_email_auth_token', ['sent'], unique=False)
    op.create_table('users_sms_auth_token',
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token', 'user_id')
    )
    op.create_index(op.f('ix_users_sms_auth_token_active'), 'users_sms_auth_token', ['active'], unique=False)
    op.create_index(op.f('ix_users_sms_auth_token_sent'), 'users_sms_auth_token', ['sent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sms_auth_token_sent'), table_name='users_sms_auth_token')
    op.drop_index(op.f('ix_users_sms_auth_token_active'), table_name='users_sms_auth_token')
    op.drop_table('users_sms_auth_token')
    op.drop_index(op.f('ix_users_email_auth_token_sent'), table_name='users_email_auth_token')
    op.drop_index(op.f('ix_users_email_auth_token_active'), table_name='users_email_auth_token')
    op.drop_table('users_email_auth_token')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
