"""Adds the end user properties table.

Revision ID: 4cbb0848ec97
Revises: 54773ddf9508
Create Date: 2018-10-22 07:35:41.858440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cbb0848ec97'
down_revision = '54773ddf9508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_user_properties',
    sa.Column('end_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('property_name', sa.String(length=511), nullable=True),
    sa.Column('property_value', sa.Text(), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ),
    sa.PrimaryKeyConstraint('end_user_id', 'property_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('end_user_properties')
    # ### end Alembic commands ###
