"""Adds created_at and updated_at and last_login_at columns to users and end_users

Revision ID: 50b5c1cb7951
Revises: 0b916a280427
Create Date: 2018-08-06 06:34:04.649609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b5c1cb7951'
down_revision = '0b916a280427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('end_users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('end_users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('orgs_client_id_key', 'orgs', type_='unique')
    op.drop_constraint('orgs_client_secret_key', 'orgs', type_='unique')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'created_at')
    op.create_unique_constraint('orgs_client_secret_key', 'orgs', ['client_secret'])
    op.create_unique_constraint('orgs_client_id_key', 'orgs', ['client_id'])
    op.drop_column('end_users', 'updated_at')
    op.drop_column('end_users', 'last_login_at')
    op.drop_column('end_users', 'created_at')
    # ### end Alembic commands ###
