"""Adds org_id to email tokens and sms tokens

Revision ID: 54773ddf9508
Revises: 50b5c1cb7951
Create Date: 2018-09-06 21:59:45.322781

"""
from alembic import op
import sqlalchemy as sa

from weasl.end_user.models import SMSToken, EmailToken


# revision identifiers, used by Alembic.
revision = '54773ddf9508'
down_revision = '50b5c1cb7951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_users_email_auth_token', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_end_users_email_auth_token_org_id'), 'end_users_email_auth_token', ['org_id'], unique=False)
    op.create_foreign_key(None, 'end_users_email_auth_token', 'orgs', ['org_id'], ['id'])
    op.add_column('end_users_sms_auth_token', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_end_users_sms_auth_token_org_id'), 'end_users_sms_auth_token', ['org_id'], unique=False)
    op.create_foreign_key(None, 'end_users_sms_auth_token', 'orgs', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'end_users_sms_auth_token', type_='foreignkey')
    op.drop_index(op.f('ix_end_users_sms_auth_token_org_id'), table_name='end_users_sms_auth_token')
    op.drop_column('end_users_sms_auth_token', 'org_id')
    op.drop_constraint(None, 'end_users_email_auth_token', type_='foreignkey')
    op.drop_index(op.f('ix_end_users_email_auth_token_org_id'), table_name='end_users_email_auth_token')
    op.drop_column('end_users_email_auth_token', 'org_id')
    # ### end Alembic commands ###
