"""Adds unique constraints and indices

Revision ID: e830eb163d38
Revises: 66fbea6238da
Create Date: 2018-07-15 21:44:55.505217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e830eb163d38'
down_revision = '66fbea6238da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_email_org_uc', 'end_users', ['org_id', 'email'])
    op.create_unique_constraint('_phone_org_uc', 'end_users', ['org_id', 'phone_number'])
    op.create_index(op.f('ix_end_users_org_id'), 'end_users', ['org_id'], unique=False)
    op.drop_index('ix_end_users_email', table_name='end_users')
    op.create_index(op.f('ix_end_users_email'), 'end_users', ['email'], unique=False)
    op.drop_index('ix_end_users_phone_number', table_name='end_users')
    op.create_index(op.f('ix_end_users_phone_number'), 'end_users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_end_users_phone_number'), table_name='end_users')
    op.create_index('ix_end_users_phone_number', 'end_users', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_end_users_email'), table_name='end_users')
    op.create_index('ix_end_users_email', 'end_users', ['email'], unique=True)
    op.drop_index(op.f('ix_end_users_org_id'), table_name='end_users')
    op.drop_constraint('_phone_org_uc', 'end_users', type_='unique')
    op.drop_constraint('_email_org_uc', 'end_users', type_='unique')
    # ### end Alembic commands ###
